### ISSUE TITLE
Implement soft delete option for secrets.

### ISSUE THREAD

**Issue by sureshg** [oneops/secrets-proxy#2]
As of today, the secret delete option (`secrets delete  -a <appname>  <secretname>`) is irrevocable. For end users, there aren't any options to recover it (though it's still in the keywhiz database, with manual surgery you can restore it) . This issue to implement an option to soft delete, so it gets removed from the nodes (`/secrets`), but still in the same application group, so the users can recover it later.

Note: Secret update operations can be reverted.

**Comment by sureshg** [comment]
@mosabua @jvanzyl

**Comment by mosabua** [comment]
I agree with this feature request but we should be tracking all this in JIRA..

**Comment by mosabua** [comment]
Closing and removing issue tracking here.
